kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mycluster
networking:
  apiServerPort: 6443
  #disableDefaultCNI: true
  podSubnet: 172.16.254.0/16
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    #hostPort: 33443
    hostPort: 443
    protocol: TCP
  - hostPort: 32225
    listenAddress: "0.0.0.0"
    containerPort: 32225
    protocol: TCP
  - hostPort: 32226
    listenAddress: "0.0.0.0"
    containerPort: 32226
    protocol: TCP
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "master=true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "worker=true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "worker=true"
